name: 'Godot Info'
description: 'Provides info regarding Godot exports.'
author: 'Pixelbyte Studios'
runs: 
  using: "node16"
  main: dist/index.js
branding:
  # icon: 'something'
  color: 'white'
inputs:
  #required
  relative_project_path:
    description: The path relative to the root of the git repository containing the "project.godot" file.
    required: true
  #optional
outputs:
  itch_project:
    description: The name of the itch project any artifacts from exporting this project should be uploaded to.
  windows_artifact:
    description: The name of the Windows artifact + .zip
  require_wine:
    description: True if there is a valid windows export, false otherwise
  html5_artifact:
    description: The name of the Html5 artifact + .zip
  osx_artifact:
    description: The name of the OSX artifact + .zip
  linux_artifact:
    description: The name of the Linux artifact + .zip
  android_artifact:
    description: The name of the Android artifact + .zip